= Gitを導入するときにやったこと
:toc: left
:toc-title: 目次
:auther: 中島慎児
:source-highlighter: coderay

GitとGitHubをプロジェクトに導入する際にやったことをメモする。 +

== はじめに

プロジェクトの初期から参画し、ある程度の舵取りができる機会に恵まれた。 +
プロジェクト参画時の状況としては以下の通り。 +

* Githubの採用は決定しているが、運用方法の詳細は決まっていない。
* Javaのチームで、人数は８人程度。
** 開発環境はこれから構築する。
** 設計担当が２名で、残りの６名がそれぞればらばらに製造を担当する。
** メンバーはGitの経験はほとんどない。

== ブランチ戦略

まず最初にブランチ戦略を決定する。 +

Gitでよく使われるブランチ戦略は、Git-Flow、Github-Flow、GitLab-Flowなどがある。 +
今回の導入には、Git-Flowを採用した。考慮した点は以下の通り。 +

* 数か月ごとにリリースがある。 +
数か月ごとにリリースがあり、リリースされたものはエンドユーザに公開されて実践に即した動作テストに使われる。 +
次のリリースまでの間は、次々と機能追加が実施される。 +
つまり、リリース済みのブランチと作業中のブランチは明確に分離して管理する必要があった。 +
* チームメンバーが一つのシステムに対して、それぞれ個別に機能追加を担当する。 +
多機能な画面が複数ある複雑なシステムを複数の人数で分担して、短期間に構築する必要があった。 +

この二つの要件を満たすのがGit-Flowだった。 +

== ツールの選定

使用するツールはlink:https://ja.atlassian.com/software/sourcetree[SourceTree]を導入した。 +
コマンドラインにこだわる必要はない。 +

複数の人員で作業すると、必ずコンフリクトを起こす。 +
それはチームメンバーの技術レベルや習熟度などとは直接の関係はなく、だれでも起こしうる事故と解釈すべき。 +
その場合、修復作業をコマンドラインでやることは、不可能ではないがそれなりの学習コストがかかる。 +
同じ低い習熟度からスタートした場合、やはりGUIがあったほうがとっかかりを得やすい。 +

== 人にやらせる前に自分で実際にやってみる

本格的な作業用リポジトリを作る前に、自分で練習用のリポジトリを作って、実際に一通りの操作を経験しておく。 +

リポジトリの内容は、特別なにかのアプリケーションでなくてもいい。

== ドキュメントを作る

自分でやってみる過程において、作業工程をテキストに記録しておく。そしてそれをもとに

== チーム内のフォロー（目の前でやってみる、個別にやる）

とにかくはじめて使う場合は不安がつきまとうので、ぶっ壊しても大丈夫という安心感を演出する。 +

Git-Flow戦略の場合は、基本的に機能追加では master ブランチは手を付けない。また、作業用である develop ブランチも、実作業は　fearture ブランチを分岐して行うので直接編集することはない。

=== 用語の解説。スタッシュ、コミット、プッシュ、プル、マージ、リベース、リモート


=== FAQ

一度のレクチャーやひとつのドキュメント公開ではきっと対応し切れない。
チームメンバーから不明点や質問があがればそれはむしろ歓迎するべき。メンバーの環境でマウスを借りて実演してること。個別に丁寧に対応することが、けっきょくは最も工数が少なくてすむ。個別に丁寧に対応していれば、やらかす前に声をかけてくれるようになるはず。

==== アンチパターン

==== マージの仕方がわかりません


==== 一部のファイルだけコミットしたいけどどうしましょう（スタッシaュ）


==== コンフリクトの解消の仕方がわかりません


==== やらかしちゃいました


===== 戻し方各種


===== リベースの使い方は慎重に


===== 作業ミスの指摘の仕方は難しい
